### ISSUE TITLE
image not change

### ISSUE THREAD

**Issue by muhammadsaddamnur** [furkansarihan/story_viewer#2]
image not change when i have image 404, even though i have set the duration

**Comment by furkansarihan** [comment]
If you mean "progress animation is not started" by "image not change"; This is the default behavior of story progress bar just like in instagram when image could not loaded.

But obviously I can provide a boolean for bypass this behaviour.

**Comment by muhammadsaddamnur** [comment]
Yes good idea.  I try to bypass your package, and it's worked

**Comment by furkansarihan** [comment]
Okay. You can create a pull request.
